In [1]:
import pandas as pd

In [2]:
watch = pd.read_csv('/Users/emilkoch/Downloads/export-6.csv')

In [3]:
watch

,index,source,timestamp,values_1
0,164349,battery,2017-06-29 07:45:56.262,['98']
1,164350,accelerometer,2017-06-29 07:46:01.263,"['-0.3440857', '0.68330383', '9.967361']"
2,164351,gravity,2017-06-29 07:46:01.324,"['-0.34131828', '0.6573288', '9.778641']"
3,164352,linear_acceleration,2017-06-29 07:46:01.329,"['-0.018068999', '0.034808993', '-0.033065796']"
4,164353,gyroscope,2017-06-29 07:46:01.402,"['0.0041656494', '-0.0132751465', '0.006164551']"
...,...,...,...,...
200466,164346,heart_rate,2017-07-13 20:21:35.060,"['56.0', '1']"
200467,150770,heart_rate,2017-07-13 20:21:35.124,"['57.0', '1']"
200468,164347,heart_rate,2017-07-13 20:21:35.124,"['57.0', '1']"
200469,150771,pressure,2017-07-13 20:21:36.105,['989.3108']
200470,164348,pressure,2017-07-13 20:21:36.105,['989.3108']

In [4]:
# Parse values in 'values_1' column to extract numerical values
watch['values_1'] = watch['values_1'].apply(lambda x: [float(val.strip("[]'")) for val in x.split(", ")])

In [5]:
# Convert the 'values_1' column to numeric if possible
watch['values_1'] = watch['values_1'].apply(pd.to_numeric, errors='coerce')

# Pivot the data to create columns for each unique source_encoded
pivot_data = pd.pivot_table(watch, 
                            values='values_1', 
                            index='timestamp', 
                            columns='source')

# Print the pivoted data
print(pivot_data)

source                                        accelerometer battery  \
timestamp
2017-06-29 07:45:56.262                                 NaN  [98.0]
2017-06-29 07:46:01.263  [-0.3440857, 0.68330383, 9.967361]     NaN
2017-06-29 07:46:01.324                                 NaN     NaN
2017-06-29 07:46:01.329                                 NaN     NaN
2017-06-29 07:46:01.402                                 NaN     NaN
...                                                     ...     ...
2017-07-13 20:21:35.009                                 NaN     NaN
2017-07-13 20:21:35.020                                 NaN     NaN
2017-07-13 20:21:35.060                                 NaN     NaN
2017-07-13 20:21:35.124                                 NaN     NaN
2017-07-13 20:21:36.105                                 NaN     NaN

source                                              gravity  \
timestamp
2017-06-29 07:45:56.262                                 NaN
2017-06-29 07:46:01.263                                 NaN
2017-06-29 07:46:01.324  [-0.34131828, 0.6573288, 9.778641]
2017-06-29 07:46:01.329                                 NaN
2017-06-29 07:46:01.402                                 NaN
...                                                     ...
2017-07-13 20:21:35.009                                 NaN
2017-07-13 20:21:35.020                                 NaN
2017-07-13 20:21:35.060                                 NaN
2017-07-13 20:21:35.124                                 NaN
2017-07-13 20:21:36.105                                 NaN

source                                                    gyroscope  \
timestamp
2017-06-29 07:45:56.262                                         NaN
2017-06-29 07:46:01.263                                         NaN
2017-06-29 07:46:01.324                                         NaN
2017-06-29 07:46:01.329                                         NaN
2017-06-29 07:46:01.402  [0.0041656494, -0.0132751465, 0.006164551]
...                                                             ...
2017-07-13 20:21:35.009                                         NaN
2017-07-13 20:21:35.020                                         NaN
2017-07-13 20:21:35.060                                         NaN
2017-07-13 20:21:35.124                                         NaN
2017-07-13 20:21:36.105                                         NaN

source                    heart_rate  \
timestamp
2017-06-29 07:45:56.262          NaN
2017-06-29 07:46:01.263          NaN
2017-06-29 07:46:01.324          NaN
2017-06-29 07:46:01.329          NaN
2017-06-29 07:46:01.402          NaN
...                              ...
2017-07-13 20:21:35.009  [54.0, 1.0]
2017-07-13 20:21:35.020  [55.0, 1.0]
2017-07-13 20:21:35.060  [56.0, 1.0]
2017-07-13 20:21:35.124  [57.0, 1.0]
2017-07-13 20:21:36.105          NaN

source                                         linear_acceleration  \
timestamp
2017-06-29 07:45:56.262                                        NaN
2017-06-29 07:46:01.263                                        NaN
2017-06-29 07:46:01.324                                        NaN
2017-06-29 07:46:01.329  [-0.018068999, 0.034808993, -0.033065796]
2017-06-29 07:46:01.402                                        NaN
...                                                            ...
2017-07-13 20:21:35.009                                        NaN
2017-07-13 20:21:35.020                                        NaN
2017-07-13 20:21:35.060                                        NaN
2017-07-13 20:21:35.124                                        NaN
2017-07-13 20:21:36.105                                        NaN

source                  magnetometer orientation    pressure rotation_vector  \
timestamp
2017-06-29 07:45:56.262          NaN         NaN         NaN             NaN
2017-06-29 07:46:01.263          NaN         NaN         NaN             NaN
2017-06-29 07:46:01.324          NaN         NaN         NaN             NaN
2017-06-29 07:46:01.329          NaN         NaN         NaN             NaN
2017-06-29 07:46:01.402          NaN         NaN         NaN             NaN
...                              ...         ...         ...             ...
2017-07-13 20:21:35.009          NaN         NaN         NaN             NaN
2017-07-13 20:21:35.020          NaN         NaN         NaN             NaN
2017-07-13 20:21:35.060          NaN         NaN         NaN             NaN
2017-07-13 20:21:35.124          NaN         NaN         NaN             NaN
2017-07-13 20:21:36.105          NaN         NaN  [989.3108]             NaN

source                  step_counter step_detector
timestamp
2017-06-29 07:45:56.262          NaN           NaN
2017-06-29 07:46:01.263          NaN           NaN
2017-06-29 07:46:01.324          NaN           NaN
2017-06-29 07:46:01.329          NaN           NaN
2017-06-29 07:46:01.402          NaN           NaN
...                              ...           ...
2017-07-13 20:21:35.009          NaN           NaN
2017-07-13 20:21:35.020          NaN           NaN
2017-07-13 20:21:35.060          NaN           NaN
2017-07-13 20:21:35.124          NaN           NaN
2017-07-13 20:21:36.105          NaN           NaN

[173662 rows x 12 columns]

In [7]:
pivot_data

source,accelerometer,battery,gravity,gyroscope,heart_rate,linear_acceleration,magnetometer,orientation,pressure,rotation_vector,step_counter,step_detector
timestamp,,,,,,,,,,,,
2017-06-29 07:45:56.262,NaN,[98.0],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-06-29 07:46:01.263,"[-0.3440857, 0.68330383, 9.967361]",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-06-29 07:46:01.324,NaN,NaN,"[-0.34131828, 0.6573288, 9.778641]",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-06-29 07:46:01.329,NaN,NaN,NaN,NaN,NaN,"[-0.018068999, 0.034808993, -0.033065796]",NaN,NaN,NaN,NaN,NaN,NaN
2017-06-29 07:46:01.402,NaN,NaN,NaN,"[0.0041656494, -0.0132751465, 0.006164551]",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
2017-07-13 20:21:35.009,NaN,NaN,NaN,NaN,"[54.0, 1.0]",NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-07-13 20:21:35.020,NaN,NaN,NaN,NaN,"[55.0, 1.0]",NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-07-13 20:21:35.060,NaN,NaN,NaN,NaN,"[56.0, 1.0]",NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-07-13 20:21:35.124,NaN,NaN,NaN,NaN,"[57.0, 1.0]",NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-07-13 20:21:36.105,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[989.3108],NaN,NaN,NaN

In [6]:
pivot_data4 = pivot_data.drop(columns = ['battery', 'heart_rate', 'pressure'])

In [7]:
# Expand accelerometer column into x, y, z components
accelerometer_components = pivot_data4 ['accelerometer'].apply(pd.Series)
accelerometer_components.columns = ['accel_x', 'accel_y', 'accel_z']

# Expand gravity column into x, y, z components
gravity_components = pivot_data4 ['gravity'].apply(pd.Series)
gravity_components.columns = ['gravity_x', 'gravity_y', 'gravity_z']

# Expand gyroscope column into x, y, z components
gyroscope_components = pivot_data4 ['gyroscope'].apply(pd.Series)
gyroscope_components.columns = ['gyro_x', 'gyro_y', 'gyro_z']

# Expand linear_acceleration column into x, y, z components
linear_acceleration_components = pivot_data4 ['linear_acceleration'].apply(pd.Series)
linear_acceleration_components.columns = ['linear_accel_x', 'linear_accel_y', 'linear_accel_z']

# Expand magnetometer column into x, y, z components
magnetometer_components = pivot_data4 ['magnetometer'].apply(pd.Series)
magnetometer_components.columns = ['magnetometer_x', 'magnetometer_y', 'magnetometer_z']

# Expand orientation column into x, y, z components
orientation_components = pivot_data4['orientation'].apply(pd.Series)
orientation_components.columns = ['orientation_x', 'orientation_y', 'orientation_z']

rotation_components = pivot_data4['rotation_vector'].apply(pd.Series)
rotation_components.columns = ['rotation_scalar', 'rotation_i', 'rotation_j', 'rotation_k', 'rotation_angle']

# Concatenate the new components with the original DataFrame
pivot_data4  = pd.concat([pivot_data4 , accelerometer_components, gravity_components, gyroscope_components, linear_acceleration_components, magnetometer_components, orientation_components, rotation_components], axis=1)

# Drop the original columns
pivot_data4.drop(columns=['accelerometer', 'gravity', 'gyroscope', 'linear_acceleration', 'magnetometer', 'orientation', 'rotation_vector'], inplace=True)

# Print the updated DataFrame
print(pivot_data4)

                        step_counter step_detector   accel_x   accel_y  \
timestamp
2017-06-29 07:45:56.262          NaN           NaN       NaN       NaN
2017-06-29 07:46:01.263          NaN           NaN -0.344086  0.683304
2017-06-29 07:46:01.324          NaN           NaN       NaN       NaN
2017-06-29 07:46:01.329          NaN           NaN       NaN       NaN
2017-06-29 07:46:01.402          NaN           NaN       NaN       NaN
...                              ...           ...       ...       ...
2017-07-13 20:21:35.009          NaN           NaN       NaN       NaN
2017-07-13 20:21:35.020          NaN           NaN       NaN       NaN
2017-07-13 20:21:35.060          NaN           NaN       NaN       NaN
2017-07-13 20:21:35.124          NaN           NaN       NaN       NaN
2017-07-13 20:21:36.105          NaN           NaN       NaN       NaN

                          accel_z  gravity_x  gravity_y  gravity_z    gyro_x  \
timestamp
2017-06-29 07:45:56.262       NaN        NaN        NaN        NaN       NaN
2017-06-29 07:46:01.263  9.967361        NaN        NaN        NaN       NaN
2017-06-29 07:46:01.324       NaN  -0.341318   0.657329   9.778641       NaN
2017-06-29 07:46:01.329       NaN        NaN        NaN        NaN       NaN
2017-06-29 07:46:01.402       NaN        NaN        NaN        NaN  0.004166
...                           ...        ...        ...        ...       ...
2017-07-13 20:21:35.009       NaN        NaN        NaN        NaN       NaN
2017-07-13 20:21:35.020       NaN        NaN        NaN        NaN       NaN
2017-07-13 20:21:35.060       NaN        NaN        NaN        NaN       NaN
2017-07-13 20:21:35.124       NaN        NaN        NaN        NaN       NaN
2017-07-13 20:21:36.105       NaN        NaN        NaN        NaN       NaN

                           gyro_y  ...  magnetometer_y  magnetometer_z  \
timestamp                          ...
2017-06-29 07:45:56.262       NaN  ...             NaN             NaN
2017-06-29 07:46:01.263       NaN  ...             NaN             NaN
2017-06-29 07:46:01.324       NaN  ...             NaN             NaN
2017-06-29 07:46:01.329       NaN  ...             NaN             NaN
2017-06-29 07:46:01.402 -0.013275  ...             NaN             NaN
...                           ...  ...             ...             ...
2017-07-13 20:21:35.009       NaN  ...             NaN             NaN
2017-07-13 20:21:35.020       NaN  ...             NaN             NaN
2017-07-13 20:21:35.060       NaN  ...             NaN             NaN
2017-07-13 20:21:35.124       NaN  ...             NaN             NaN
2017-07-13 20:21:36.105       NaN  ...             NaN             NaN

                         orientation_x  orientation_y  orientation_z  \
timestamp
2017-06-29 07:45:56.262            NaN            NaN            NaN
2017-06-29 07:46:01.263            NaN            NaN            NaN
2017-06-29 07:46:01.324            NaN            NaN            NaN
2017-06-29 07:46:01.329            NaN            NaN            NaN
2017-06-29 07:46:01.402            NaN            NaN            NaN
...                                ...            ...            ...
2017-07-13 20:21:35.009            NaN            NaN            NaN
2017-07-13 20:21:35.020            NaN            NaN            NaN
2017-07-13 20:21:35.060            NaN            NaN            NaN
2017-07-13 20:21:35.124            NaN            NaN            NaN
2017-07-13 20:21:36.105            NaN            NaN            NaN

                         rotation_scalar  rotation_i  rotation_j  rotation_k  \
timestamp
2017-06-29 07:45:56.262              NaN         NaN         NaN         NaN
2017-06-29 07:46:01.263              NaN         NaN         NaN         NaN
2017-06-29 07:46:01.324              NaN         NaN         NaN         NaN
2017-06-29 07:46:01.329              NaN         NaN         NaN         NaN
2017-06-29 07:46:01.402              NaN         NaN         NaN         NaN
...                                  ...         ...         ...         ...
2017-07-13 20:21:35.009              NaN         NaN         NaN         NaN
2017-07-13 20:21:35.020              NaN         NaN         NaN         NaN
2017-07-13 20:21:35.060              NaN         NaN         NaN         NaN
2017-07-13 20:21:35.124              NaN         NaN         NaN         NaN
2017-07-13 20:21:36.105              NaN         NaN         NaN         NaN

                         rotation_angle
timestamp
2017-06-29 07:45:56.262             NaN
2017-06-29 07:46:01.263             NaN
2017-06-29 07:46:01.324             NaN
2017-06-29 07:46:01.329             NaN
2017-06-29 07:46:01.402             NaN
...                                 ...
2017-07-13 20:21:35.009             NaN
2017-07-13 20:21:35.020             NaN
2017-07-13 20:21:35.060             NaN
2017-07-13 20:21:35.124             NaN
2017-07-13 20:21:36.105             NaN

[173662 rows x 25 columns]

In [8]:
pivot_data4

,step_counter,step_detector,accel_x,accel_y,accel_z,gravity_x,gravity_y,gravity_z,gyro_x,gyro_y,...,magnetometer_y,magnetometer_z,orientation_x,orientation_y,orientation_z,rotation_scalar,rotation_i,rotation_j,rotation_k,rotation_angle
timestamp,,,,,,,,,,,,,,,,,,,,,
2017-06-29 07:45:56.262,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-06-29 07:46:01.263,NaN,NaN,-0.344086,0.683304,9.967361,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-06-29 07:46:01.324,NaN,NaN,NaN,NaN,NaN,-0.341318,0.657329,9.778641,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-06-29 07:46:01.329,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-06-29 07:46:01.402,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.004166,-0.013275,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2017-07-13 20:21:35.009,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-07-13 20:21:35.020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-07-13 20:21:35.060,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-07-13 20:21:35.124,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-07-13 20:21:36.105,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
# Remove duplicate columns, if any
pivot_data4 = pivot_data4.loc[:, ~pivot_data4.columns.duplicated()]
# Replace NaN values with 0s
pivot_data4.fillna(0, inplace=True)

In [12]:
# Convert the values in 'step_detector' column to strings
pivot_data4['step_detector'] = pivot_data4['step_detector'].astype(str)

# Remove square brackets and single quotes from the values in 'step_detector' column
pivot_data4['step_detector'] = pivot_data4['step_detector'].str.strip("[]").str.replace("'", "")

# Convert the values in 'step_detector' column to float
pivot_data4['step_detector'] = pivot_data4['step_detector'].astype(float)

In [13]:
# Convert the values in 'step_detector' column to strings
pivot_data4['step_counter'] = pivot_data4['step_counter'].astype(str)

# Remove square brackets and single quotes from the values in 'step_detector' column
pivot_data4['step_counter'] = pivot_data4['step_counter'].str.strip("[]").str.replace("'", "")

# Convert the values in 'step_detector' column to float
pivot_data4['step_counter'] = pivot_data4['step_counter'].astype(float)

In [14]:
pivot_data4

,step_counter,step_detector,accel_x,accel_y,accel_z,gravity_x,gravity_y,gravity_z,gyro_x,gyro_y,...,magnetometer_y,magnetometer_z,orientation_x,orientation_y,orientation_z,rotation_scalar,rotation_i,rotation_j,rotation_k,rotation_angle
timestamp,,,,,,,,,,,,,,,,,,,,,
2017-06-29 07:45:56.262,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2017-06-29 07:46:01.263,0.0,0.0,-0.344086,0.683304,9.967361,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2017-06-29 07:46:01.324,0.0,0.0,0.000000,0.000000,0.000000,-0.341318,0.657329,9.778641,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2017-06-29 07:46:01.329,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2017-06-29 07:46:01.402,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.004166,-0.013275,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2017-07-13 20:21:35.009,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2017-07-13 20:21:35.020,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2017-07-13 20:21:35.060,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2017-07-13 20:21:35.124,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2017-07-13 20:21:36.105,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [20]:
smartphone = pd.read_csv('/Users/emilkoch/Desktop/2Tango/Data Files/Dataset_2_glasses/pivot_table_s_split.csv')

/var/folders/4r/5qs7726s3_dc54vtgh1sc2740000gn/T/ipykernel_7579/94197935.py:1: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  smartphone = pd.read_csv('/Users/emilkoch/Desktop/2Tango/Data Files/Dataset_2_glasses/pivot_table_s_split.csv')

In [21]:
smartphone

,timestamp,step_detector_values,audio_value_1,audio_value_2,audio_value_3,audio_value_4,activity_type
0,2017-06-29 07:45:16.506,1.0,0.0,0.00000,0.0,0.0,Video games
1,2017-06-29 07:45:17.407,0.0,0.0,0.00000,0.0,32767.0,In computer
2,2017-06-29 07:45:18.407,0.0,227.0,113.50000,227.0,227.0,At home
3,2017-06-29 07:45:19.407,0.0,590.0,272.33334,590.0,227.0,In computer
4,2017-06-29 07:45:20.446,0.0,1724.0,635.25000,1724.0,227.0,Eat
...,...,...,...,...,...,...,...
617948,2017-07-13 20:13:33.671,0.0,1956.0,5246.24850,32767.0,30.0,0
617949,2017-07-13 20:13:34.663,0.0,2673.0,5246.18160,32767.0,30.0,0
617950,2017-07-13 20:13:35.663,0.0,2340.0,5246.10640,32767.0,30.0,0
617951,2017-07-13 20:13:36.668,0.0,2046.0,5246.02400,32767.0,30.0,0
617952,2017-07-13 20:13:37.668,0.0,2441.0,5245.95170,32767.0,30.0,0

In [26]:
# Filter the DataFrame to keep rows where both "activity" and "duration" are not equal to 0
smartphone2 = smartphone[(smartphone['activity_type'] != 0)]

In [27]:
smartphone2

,timestamp,step_detector_values,audio_value_1,audio_value_2,audio_value_3,audio_value_4,activity_type
0,2017-06-29 07:45:16.506,1.0,0.0,0.00000,0.0,0.0,Video games
1,2017-06-29 07:45:17.407,0.0,0.0,0.00000,0.0,32767.0,In computer
2,2017-06-29 07:45:18.407,0.0,227.0,113.50000,227.0,227.0,At home
3,2017-06-29 07:45:19.407,0.0,590.0,272.33334,590.0,227.0,In computer
4,2017-06-29 07:45:20.446,0.0,1724.0,635.25000,1724.0,227.0,Eat
...,...,...,...,...,...,...,...
131067,2017-07-02 11:41:07.180,1.0,0.0,0.00000,0.0,0.0,0
131068,2017-07-02 11:41:07.422,1.0,0.0,0.00000,0.0,0.0,0
131069,2017-07-02 11:41:07.617,0.0,3520.0,11003.53100,32767.0,48.0,0
131070,2017-07-02 11:41:08.503,1.0,0.0,0.00000,0.0,0.0,0
131071,2017-07-02 11:41:08.618,0.0,6442.0,11003.03000,32767.0,48.0,0