In [2]:
import pandas as pd 
import numpy as np

In [67]:
pivot_data = pd.read_csv('/Users/emilkoch/Desktop/2Tango/Data Files/Dataset_2_glasses/pivot_data.csv')
pivot_table_s = pd.read_csv('/Users/emilkoch/Desktop/2Tango/Data Files/Dataset_2_glasses/pivot_table_s.csv')
merged_data_s = pd.read_csv('/Users/emilkoch/Desktop/2Tango/Data Files/Dataset_2_glasses/merged_data_s.csv')
merged_data_s_f = pd.read_csv('/Users/emilkoch/Desktop/2Tango/Data Files/Dataset_2_glasses/merged_data_s_f.csv')
merged_data_s_f1 = pd.read_csv('/Users/emilkoch/Desktop/2Tango/Data Files/Dataset_2_glasses/merged_data_s_f1.csv')
filtered_merged_data_s_f1 = pd.read_csv('/Users/emilkoch/Desktop/2Tango/Data Files/Dataset_2_glasses/filtered_merged_data_s_f1.csv')
filtered_merged_data_s_f2 = pd.read_csv('/Users/emilkoch/Desktop/2Tango/Data Files/Dataset_2_glasses/filtered_merged_data_s_f2.csv')
filtered_data_glasses = pd.read_csv('/Users/emilkoch/Desktop/2Tango/Data Files/Dataset_2_glasses/filtered_data_glasses.csv')
filtered_merged_data_glasses = pd.read_csv('/Users/emilkoch/Desktop/2Tango/Data Files/Dataset_2_glasses/filtered_merged_data_glasses.csv')
glasses = pd.read_csv('/Users/emilkoch/Desktop/2Tango/Data Files/Dataset_2_glasses/glasses.csv')
smartwatch_sources = pd.read_csv('/Users/emilkoch/Desktop/2Tango/Data Files/Dataset_2_glasses/source_smartwatch_full.csv')
activity_type_full = pd.read_csv('/Users/emilkoch/Desktop/2Tango/Data Files/Dataset_2_glasses/report_full_activity_type.csv')
smartphone_full = pd.read_csv('/Users/emilkoch/Desktop/2Tango/Data Files/Dataset_2_glasses/smartphone_full.csv')

In [6]:
merged_data_s_f1['duration_numeric'] = merged_data_s_f1['duration'].astype(str).str.split(':').apply(lambda x: int(x[0]) * 60 + int(x[1]) if len(x) == 2 else np.nan)
merged_data_s_f1.drop(columns = ['duration'])

,timestamp,accel_x,accel_y,accel_z,gravity_x,gravity_y,gravity_z,gyro_x,gyro_y,gyro_z,linear_accel_x,linear_accel_y,linear_accel_z,step_detector_values,audio_value_1,audio_value_2,audio_value_3,audio_value_4,activity_type,duration_numeric
0,2017-06-29 09:57:00.280,0.00000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,1.0,0.0,0.0000,0.0,0.0,Eat,20.0
1,2017-06-29 09:57:00.448,0.00000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,8513.0,7546.2360,32767.0,45.0,Eat,20.0
2,2017-06-29 09:57:01.000,0.00000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,1.0,0.0,0.0000,0.0,0.0,Eat,20.0
3,2017-06-29 09:57:01.447,0.00000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,8273.0,7546.3276,32767.0,45.0,Eat,20.0
4,2017-06-29 09:57:01.521,0.00000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,1.0,0.0,0.0000,0.0,0.0,Eat,20.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
629787,2017-07-13 20:13:35.663,0.00000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,2340.0,5246.1064,32767.0,30.0,Video games,41.0
629788,2017-07-13 20:13:36.668,0.00000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,2046.0,5246.0240,32767.0,30.0,Video games,41.0
629789,2017-07-13 20:13:37.668,0.00000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,2441.0,5245.9517,32767.0,30.0,Video games,41.0
629790,2017-07-13 20:21:31.322,0.00000,0.000000,0.000000,0.0,0.0,0.0,-0.387283,0.058716,0.566345,0.0,0.0,0.0,0.0,0.0,0.0000,0.0,0.0,0,NaN
629791,2017-07-13 20:21:31.358,-0.67569,2.700424,10.965744,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0000,0.0,0.0,0,NaN

In [15]:
pivot_data

,timestamp,duration,accel_x,accel_y,accel_z,gravity_x,gravity_y,gravity_z,gyro_x,gyro_y,gyro_z,linear_accel_x,linear_accel_y,linear_accel_z,activity_type
0,2017-06-29 09:57:08.396,00:20,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-0.351562,0.686813,0.476898,0.000000,0.000000,0.000000,Eat
1,2017-06-29 09:57:08.406,00:20,-10.173126,-1.471237,1.924393,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,Eat
2,2017-06-29 09:57:08.589,00:20,0.000000,0.000000,0.000000,4.585228,-8.101572,3.083927,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,Eat
3,2017-06-29 09:57:08.591,00:20,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-0.280773,-0.710495,-0.692953,Eat
4,2017-06-29 09:57:13.436,00:20,4.726227,-10.251968,0.491104,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,Eat
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24898,2017-07-13 20:03:58.637,00:41,-2.270111,-8.976822,-3.034347,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,Video games
24899,2017-07-13 20:05:00.880,00:41,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.075684,-0.002960,0.047028,0.000000,0.000000,0.000000,Video games
24900,2017-07-13 20:05:00.933,00:41,-3.145065,-8.022736,-4.604950,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,Video games
24901,2017-07-13 20:21:31.322,00:41,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-0.387283,0.058716,0.566345,0.000000,0.000000,0.000000,Video games
24902,2017-07-13 20:21:31.358,00:41,-0.675690,2.700424,10.965744,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,Video games

In [22]:
pivot_data['duration_numeric'] = pivot_data['duration'].astype(str).str.split(':').apply(lambda x: int(x[0]) * 60 + int(x[1]) if len(x) == 2 else np.nan)
pivot_data= pivot_data.drop(columns = ['duration'])

In [23]:
from sklearn.preprocessing import LabelEncoder
import joblib

# Create and fit the LabelEncoder
label_encoder_smartwatch= LabelEncoder()
pivot_data['activity_encoded'] = label_encoder_smartwatch.fit_transform(pivot_data['activity_type'])

# Save the LabelEncoder to a file
joblib.dump(label_encoder_smartwatch, '/Users/emilkoch/Desktop/2Tango/messenger/Research/Job_Library/label_encoder_label_encoder_smartwatch.pkl')

['/Users/emilkoch/Desktop/2Tango/messenger/Research/Job_Library/label_encoder_label_encoder_smartwatch.pkl']

In [24]:
pivot_data

,timestamp,accel_x,accel_y,accel_z,gravity_x,gravity_y,gravity_z,gyro_x,gyro_y,gyro_z,linear_accel_x,linear_accel_y,linear_accel_z,activity_type,duration_numeric,activity_encoded
0,2017-06-29 09:57:08.396,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-0.351562,0.686813,0.476898,0.000000,0.000000,0.000000,Eat,20,2
1,2017-06-29 09:57:08.406,-10.173126,-1.471237,1.924393,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,Eat,20,2
2,2017-06-29 09:57:08.589,0.000000,0.000000,0.000000,4.585228,-8.101572,3.083927,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,Eat,20,2
3,2017-06-29 09:57:08.591,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-0.280773,-0.710495,-0.692953,Eat,20,2
4,2017-06-29 09:57:13.436,4.726227,-10.251968,0.491104,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,Eat,20,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24898,2017-07-13 20:03:58.637,-2.270111,-8.976822,-3.034347,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,Video games,41,18
24899,2017-07-13 20:05:00.880,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.075684,-0.002960,0.047028,0.000000,0.000000,0.000000,Video games,41,18
24900,2017-07-13 20:05:00.933,-3.145065,-8.022736,-4.604950,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,Video games,41,18
24901,2017-07-13 20:21:31.322,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-0.387283,0.058716,0.566345,0.000000,0.000000,0.000000,Video games,41,18
24902,2017-07-13 20:21:31.358,-0.675690,2.700424,10.965744,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,Video games,41,18

In [26]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from tensorflow.keras.models import load_model, save_model
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from keras.layers import Dense, Dropout, BatchNormalization
from sklearn.metrics import classification_report
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.utils.class_weight import compute_class_weight


# Split the data into features (X) and target variable (y)
X = pivot_data[['accel_x', 'accel_z', 'accel_y', 'gyro_x', 'gyro_y', 'gyro_z', 'duration_numeric']]
y = pivot_data['activity_encoded']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Further split the training data into training and validation sets
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.2, random_state=42)

# Standardize the features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_val_scaled = scaler.transform(X_val)
X_test_scaled = scaler.transform(X_test)

# Define the model
model = Sequential([
    Dense(64, activation='relu', input_shape=(X_train_scaled.shape[1],)),
    Dropout(0.5),
    BatchNormalization(),
    Dense(64, activation='relu'),
    Dropout(0.5),
    BatchNormalization(),
    Dense(len(np.unique(y_train)), activation='softmax') 
])

# Compile the model
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])


# Encode class labels
le = LabelEncoder()
y_train_encoded = le.fit_transform(y_train)

# Compute class weights using the encoded labels
class_weights = compute_class_weight(class_weight='balanced', classes=np.unique(y_train_encoded), y=y_train_encoded)

# Create a class weight dictionary
class_weight_dict = dict(zip(le.transform(le.classes_), class_weights))

# Train the model with class weights and early stopping
history = model.fit(X_train_scaled, y_train_encoded, epochs=50, validation_data=(X_val_scaled, y_val), class_weight=class_weight_dict)

# Save the model
file_path = "/Users/emilkoch/Desktop/2Tango/messenger/research/Model_Save/smartwatch.keras"
save_model(model, file_path)

# Evaluate the model on the test set
test_loss, test_accuracy = model.evaluate(X_test_scaled, y_test)
print("Test Accuracy:", test_accuracy)

# Make predictions
y_pred_prob = model.predict(X_test_scaled)
y_pred = np.argmax(y_pred_prob, axis=1)

# Calculate precision, recall, and F1 score
report = classification_report(y_test, y_pred)
print(report)

Epoch 1/50
499/499 [==============================] - 5s 4ms/step - loss: 3.2123 - accuracy: 0.0813 - val_loss: 2.7513 - val_accuracy: 0.0946
Epoch 2/50
499/499 [==============================] - 2s 4ms/step - loss: 2.8022 - accuracy: 0.0887 - val_loss: 2.6130 - val_accuracy: 0.0994
Epoch 3/50
499/499 [==============================] - 2s 4ms/step - loss: 2.6124 - accuracy: 0.0909 - val_loss: 2.5202 - val_accuracy: 0.1262
Epoch 4/50
499/499 [==============================] - 2s 4ms/step - loss: 2.4793 - accuracy: 0.0972 - val_loss: 2.4214 - val_accuracy: 0.1368
Epoch 5/50
499/499 [==============================] - 2s 4ms/step - loss: 2.3980 - accuracy: 0.1013 - val_loss: 2.3416 - val_accuracy: 0.1719
Epoch 6/50
499/499 [==============================] - 2s 4ms/step - loss: 2.3295 - accuracy: 0.1095 - val_loss: 2.3590 - val_accuracy: 0.1491
Epoch 7/50
499/499 [==============================] - 2s 4ms/step - loss: 2.3016 - accuracy: 0.1054 - val_loss: 2.3125 - val_accuracy: 0.1513
Epoch 8/50
499/499 [==============================] - 2s 4ms/step - loss: 2.2641 - accuracy: 0.1113 - val_loss: 2.2751 - val_accuracy: 0.1849
Epoch 9/50
499/499 [==============================] - 2s 4ms/step - loss: 2.2225 - accuracy: 0.1199 - val_loss: 2.2718 - val_accuracy: 0.1220
Epoch 10/50
499/499 [==============================] - 2s 4ms/step - loss: 2.1732 - accuracy: 0.1235 - val_loss: 2.2381 - val_accuracy: 0.1458
Epoch 11/50
499/499 [==============================] - 2s 4ms/step - loss: 2.1536 - accuracy: 0.1246 - val_loss: 2.1747 - val_accuracy: 0.2000
Epoch 12/50
499/499 [==============================] - 2s 4ms/step - loss: 2.1263 - accuracy: 0.1348 - val_loss: 2.1979 - val_accuracy: 0.1859
Epoch 13/50
499/499 [==============================] - 2s 4ms/step - loss: 2.0967 - accuracy: 0.1463 - val_loss: 2.1668 - val_accuracy: 0.1862
Epoch 14/50
499/499 [==============================] - 2s 4ms/step - loss: 2.0708 - accuracy: 0.1474 - val_loss: 2.1415 - val_accuracy: 0.2266
Epoch 15/50
499/499 [==============================] - 2s 4ms/step - loss: 2.0432 - accuracy: 0.1561 - val_loss: 2.1007 - val_accuracy: 0.2296
Epoch 16/50
499/499 [==============================] - 2s 4ms/step - loss: 2.0497 - accuracy: 0.1522 - val_loss: 2.1040 - val_accuracy: 0.2098
Epoch 17/50
499/499 [==============================] - 2s 4ms/step - loss: 2.0483 - accuracy: 0.1493 - val_loss: 2.1037 - val_accuracy: 0.2078
Epoch 18/50
499/499 [==============================] - 2s 4ms/step - loss: 2.0103 - accuracy: 0.1544 - val_loss: 2.0731 - val_accuracy: 0.2228
Epoch 19/50
499/499 [==============================] - 2s 4ms/step - loss: 1.9914 - accuracy: 0.1615 - val_loss: 2.0148 - val_accuracy: 0.1960
Epoch 20/50
499/499 [==============================] - 2s 4ms/step - loss: 2.0120 - accuracy: 0.1662 - val_loss: 2.0205 - val_accuracy: 0.2311
Epoch 21/50
499/499 [==============================] - 2s 4ms/step - loss: 1.9921 - accuracy: 0.1583 - val_loss: 2.0282 - val_accuracy: 0.2424
Epoch 22/50
499/499 [==============================] - 2s 4ms/step - loss: 1.9615 - accuracy: 0.1631 - val_loss: 1.9847 - val_accuracy: 0.2550
Epoch 23/50
499/499 [==============================] - 2s 4ms/step - loss: 1.9542 - accuracy: 0.1682 - val_loss: 2.0301 - val_accuracy: 0.2005
Epoch 24/50
499/499 [==============================] - 2s 4ms/step - loss: 1.9508 - accuracy: 0.1682 - val_loss: 1.9945 - val_accuracy: 0.2356
Epoch 25/50
499/499 [==============================] - 2s 4ms/step - loss: 1.9320 - accuracy: 0.1763 - val_loss: 2.0560 - val_accuracy: 0.2296
Epoch 26/50
499/499 [==============================] - 2s 4ms/step - loss: 1.9236 - accuracy: 0.1793 - val_loss: 1.9844 - val_accuracy: 0.2291
Epoch 27/50
499/499 [==============================] - 2s 4ms/step - loss: 1.9264 - accuracy: 0.1810 - val_loss: 1.9840 - val_accuracy: 0.1822
Epoch 28/50
499/499 [==============================] - 2s 4ms/step - loss: 1.9025 - accuracy: 0.1851 - val_loss: 1.9851 - val_accuracy: 0.2035
Epoch 29/50
499/499 [==============================] - 2s 4ms/step - loss: 1.9006 - accuracy: 0.1837 - val_loss: 1.9602 - val_accuracy: 0.2467
Epoch 30/50
499/499 [==============================] - 2s 4ms/step - loss: 1.9186 - accuracy: 0.1843 - val_loss: 1.9876 - val_accuracy: 0.1977
Epoch 31/50
499/499 [==============================] - 2s 4ms/step - loss: 1.8939 - accuracy: 0.1828 - val_loss: 1.9217 - val_accuracy: 0.2228
Epoch 32/50
499/499 [==============================] - 2s 4ms/step - loss: 1.8653 - accuracy: 0.1938 - val_loss: 1.9512 - val_accuracy: 0.2439
Epoch 33/50
499/499 [==============================] - 2s 4ms/step - loss: 1.8532 - accuracy: 0.1949 - val_loss: 1.9972 - val_accuracy: 0.2296
Epoch 34/50
499/499 [==============================] - 2s 4ms/step - loss: 1.8811 - accuracy: 0.1924 - val_loss: 1.9625 - val_accuracy: 0.1834
Epoch 35/50
499/499 [==============================] - 2s 4ms/step - loss: 1.8979 - accuracy: 0.1886 - val_loss: 1.9033 - val_accuracy: 0.2346
Epoch 36/50
499/499 [==============================] - 2s 4ms/step - loss: 1.8830 - accuracy: 0.1983 - val_loss: 1.9846 - val_accuracy: 0.2118
Epoch 37/50
499/499 [==============================] - 2s 4ms/step - loss: 1.8520 - accuracy: 0.1929 - val_loss: 1.9337 - val_accuracy: 0.2605
Epoch 38/50
499/499 [==============================] - 2s 5ms/step - loss: 1.8666 - accuracy: 0.1965 - val_loss: 1.9163 - val_accuracy: 0.2487
Epoch 39/50
499/499 [==============================] - 2s 4ms/step - loss: 1.8762 - accuracy: 0.2018 - val_loss: 1.8934 - val_accuracy: 0.2223
Epoch 40/50
499/499 [==============================] - 2s 4ms/step - loss: 1.8541 - accuracy: 0.1981 - val_loss: 1.8810 - val_accuracy: 0.2668
Epoch 41/50
499/499 [==============================] - 2s 4ms/step - loss: 1.8791 - accuracy: 0.2003 - val_loss: 1.9175 - val_accuracy: 0.2743
Epoch 42/50
499/499 [==============================] - 2s 4ms/step - loss: 1.8519 - accuracy: 0.1960 - val_loss: 1.9705 - val_accuracy: 0.2309
Epoch 43/50
499/499 [==============================] - 2s 4ms/step - loss: 1.8401 - accuracy: 0.1972 - val_loss: 1.8810 - val_accuracy: 0.2474
Epoch 44/50
499/499 [==============================] - 2s 4ms/step - loss: 1.8335 - accuracy: 0.2019 - val_loss: 1.9291 - val_accuracy: 0.1937
Epoch 45/50
499/499 [==============================] - 2s 4ms/step - loss: 1.8800 - accuracy: 0.1959 - val_loss: 1.8822 - val_accuracy: 0.2289
Epoch 46/50
499/499 [==============================] - 2s 4ms/step - loss: 1.8228 - accuracy: 0.2138 - val_loss: 1.9421 - val_accuracy: 0.2123
Epoch 47/50
499/499 [==============================] - 2s 4ms/step - loss: 1.8422 - accuracy: 0.1995 - val_loss: 1.9351 - val_accuracy: 0.2434
Epoch 48/50
499/499 [==============================] - 2s 5ms/step - loss: 1.8777 - accuracy: 0.1997 - val_loss: 1.8890 - val_accuracy: 0.2645
Epoch 49/50
499/499 [==============================] - 2s 4ms/step - loss: 1.8331 - accuracy: 0.1975 - val_loss: 1.8681 - val_accuracy: 0.2600
Epoch 50/50
499/499 [==============================] - 2s 4ms/step - loss: 1.8191 - accuracy: 0.1966 - val_loss: 1.8855 - val_accuracy: 0.2354
156/156 [==============================] - 0s 2ms/step - loss: 1.8536 - accuracy: 0.2455
Test Accuracy: 0.2455330193042755
156/156 [==============================] - 0s 2ms/step
              precision    recall  f1-score   support

           0       1.00      0.04      0.08       328
           1       0.19      0.61      0.29       132
           2       0.76      0.01      0.03       893
           3       0.40      0.99      0.57       164
           4       0.71      0.01      0.02       579
           5       0.96      0.14      0.24       573
           6       0.00      0.00      0.00       151
           7       0.00      0.00      0.00       141
           8       0.08      0.05      0.06       107
           9       0.02      1.00      0.04         5
          10       0.04      0.26      0.06        46
          11       0.08      0.89      0.14        18
          12       0.35      0.86      0.50       115
          13       0.11      0.77      0.19        81
          14       0.04      0.88      0.07        42
          15       0.40      0.98      0.57        52
          16       0.42      1.00      0.59       117
          17       0.15      0.08      0.11       142
          18       0.74      0.38      0.50       439
          19       0.33      0.10      0.16       470
          20       0.86      0.55      0.67       317
          21       0.36      1.00      0.53        33
          22       0.15      0.97      0.26        36

    accuracy                           0.25      4981
   macro avg       0.35      0.50      0.25      4981
weighted avg       0.60      0.25      0.21      4981

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

A model tailored to smartwatch data.

In [32]:
merged_data_s_f

,timestamp,step_detector_values,audio_value_1,audio_value_2,audio_value_3,audio_value_4,activity_type,duration
0,2017-06-29 09:57:00.280,1.0,0.0,0.0000,0.0,0.0,Eat,00:20
1,2017-06-29 09:57:00.448,0.0,8513.0,7546.2360,32767.0,45.0,Eat,00:20
2,2017-06-29 09:57:01.000,1.0,0.0,0.0000,0.0,0.0,Eat,00:20
3,2017-06-29 09:57:01.447,0.0,8273.0,7546.3276,32767.0,45.0,Eat,00:20
4,2017-06-29 09:57:01.521,1.0,0.0,0.0000,0.0,0.0,Eat,00:20
...,...,...,...,...,...,...,...,...
604918,2017-07-13 20:13:33.671,0.0,1956.0,5246.2485,32767.0,30.0,Video games,00:41
604919,2017-07-13 20:13:34.663,0.0,2673.0,5246.1816,32767.0,30.0,Video games,00:41
604920,2017-07-13 20:13:35.663,0.0,2340.0,5246.1064,32767.0,30.0,Video games,00:41
604921,2017-07-13 20:13:36.668,0.0,2046.0,5246.0240,32767.0,30.0,Video games,00:41
604922,2017-07-13 20:13:37.668,0.0,2441.0,5245.9517,32767.0,30.0,Video games,00:41

merged_data_s_f only contains smartphone data with activity types non-zeroe. This will allow us to test separate models on smartwatch, smartphone, and smartglasses.

In [33]:
merged_data_s_f['duration_numeric'] = merged_data_s_f['duration'].astype(str).str.split(':').apply(lambda x: int(x[0]) * 60 + int(x[1]) if len(x) == 2 else np.nan)
merged_data_s_f = merged_data_s_f.drop(columns = ['duration'])

In [34]:
merged_data_s_f

,timestamp,step_detector_values,audio_value_1,audio_value_2,audio_value_3,audio_value_4,activity_type,duration_numeric
0,2017-06-29 09:57:00.280,1.0,0.0,0.0000,0.0,0.0,Eat,20
1,2017-06-29 09:57:00.448,0.0,8513.0,7546.2360,32767.0,45.0,Eat,20
2,2017-06-29 09:57:01.000,1.0,0.0,0.0000,0.0,0.0,Eat,20
3,2017-06-29 09:57:01.447,0.0,8273.0,7546.3276,32767.0,45.0,Eat,20
4,2017-06-29 09:57:01.521,1.0,0.0,0.0000,0.0,0.0,Eat,20
...,...,...,...,...,...,...,...,...
604918,2017-07-13 20:13:33.671,0.0,1956.0,5246.2485,32767.0,30.0,Video games,41
604919,2017-07-13 20:13:34.663,0.0,2673.0,5246.1816,32767.0,30.0,Video games,41
604920,2017-07-13 20:13:35.663,0.0,2340.0,5246.1064,32767.0,30.0,Video games,41
604921,2017-07-13 20:13:36.668,0.0,2046.0,5246.0240,32767.0,30.0,Video games,41
604922,2017-07-13 20:13:37.668,0.0,2441.0,5245.9517,32767.0,30.0,Video games,41

In [35]:
from sklearn.preprocessing import LabelEncoder
import joblib

# Create and fit the LabelEncoder
label_encoder_smartphone= LabelEncoder()
merged_data_s_f['activity_encoded'] = label_encoder_smartphone.fit_transform(merged_data_s_f['activity_type'])

# Save the LabelEncoder to a file
joblib.dump(label_encoder_smartphone, '/Users/emilkoch/Desktop/2Tango/messenger/Research/Job_Library/label_encoder_label_encoder_smartphone.pkl')

['/Users/emilkoch/Desktop/2Tango/messenger/Research/Job_Library/label_encoder_label_encoder_smartphone.pkl']

In [41]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from tensorflow.keras.models import load_model, save_model
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from keras.layers import Dense, Dropout, BatchNormalization
from sklearn.metrics import classification_report
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.utils.class_weight import compute_class_weight


# Split the data into features (X) and target variable (y)
X = merged_data_s_f[['duration_numeric', 'step_detector_values', 'audio_value_1', 'audio_value_2', 'audio_value_3', 'audio_value_4']]
y = merged_data_s_f['activity_encoded']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Further split the training data into training and validation sets
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.2, random_state=42)

# Standardize the features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_val_scaled = scaler.transform(X_val)
X_test_scaled = scaler.transform(X_test)

# Define the model
model = Sequential([
    Dense(64, activation='relu', input_shape=(X_train_scaled.shape[1],)),
    Dropout(0.5),
    BatchNormalization(),
    Dense(64, activation='relu'),
    Dropout(0.5),
    BatchNormalization(),
    Dense(len(np.unique(y_train)), activation='softmax') 
])

# Compile the model
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])


# Encode class labels
le = LabelEncoder()
y_train_encoded = le.fit_transform(y_train)

# Compute class weights using the encoded labels
class_weights = compute_class_weight(class_weight='balanced', classes=np.unique(y_train_encoded), y=y_train_encoded)

# Create a class weight dictionary
class_weight_dict = dict(zip(le.transform(le.classes_), class_weights))

# Train the model with class weights and early stopping
history = model.fit(X_train_scaled, y_train_encoded, epochs=20, validation_data=(X_val_scaled, y_val), class_weight=class_weight_dict)

# Save the model
file_path = "/Users/emilkoch/Desktop/2Tango/messenger/research/Model_Save/smartphone.keras"
save_model(model, file_path)

# Evaluate the model on the test set
test_loss, test_accuracy = model.evaluate(X_test_scaled, y_test)
print("Test Accuracy:", test_accuracy)

# Make predictions
y_pred_prob = model.predict(X_test_scaled)
y_pred = np.argmax(y_pred_prob, axis=1)

# Calculate precision, recall, and F1 score
report = classification_report(y_test, y_pred)
print(report)

Epoch 1/20
12099/12099 [==============================] - 47s 4ms/step - loss: 1.8101 - accuracy: 0.2693 - val_loss: 1.6372 - val_accuracy: 0.3857
Epoch 2/20
12099/12099 [==============================] - 46s 4ms/step - loss: 1.4350 - accuracy: 0.3518 - val_loss: 1.4050 - val_accuracy: 0.4743
Epoch 3/20
12099/12099 [==============================] - 47s 4ms/step - loss: 1.3669 - accuracy: 0.3675 - val_loss: 1.4094 - val_accuracy: 0.4758
Epoch 4/20
12099/12099 [==============================] - 46s 4ms/step - loss: 1.3312 - accuracy: 0.3749 - val_loss: 1.3416 - val_accuracy: 0.4776
Epoch 5/20
12099/12099 [==============================] - 44s 4ms/step - loss: 1.3154 - accuracy: 0.3813 - val_loss: 1.3942 - val_accuracy: 0.4936
Epoch 6/20
12099/12099 [==============================] - 48s 4ms/step - loss: 1.3018 - accuracy: 0.3843 - val_loss: 1.3186 - val_accuracy: 0.5314
Epoch 7/20
12099/12099 [==============================] - 46s 4ms/step - loss: 1.2838 - accuracy: 0.3865 - val_loss: 1.4803 - val_accuracy: 0.4405
Epoch 8/20
12099/12099 [==============================] - 47s 4ms/step - loss: 1.2826 - accuracy: 0.3911 - val_loss: 1.3468 - val_accuracy: 0.5227
Epoch 9/20
12099/12099 [==============================] - 46s 4ms/step - loss: 1.2701 - accuracy: 0.3909 - val_loss: 1.2841 - val_accuracy: 0.4968
Epoch 10/20
12099/12099 [==============================] - 445s 37ms/step - loss: 1.2652 - accuracy: 0.3950 - val_loss: 1.2986 - val_accuracy: 0.5272
Epoch 11/20
12099/12099 [==============================] - 49s 4ms/step - loss: 1.2565 - accuracy: 0.3976 - val_loss: 1.3210 - val_accuracy: 0.5311
Epoch 12/20
12099/12099 [==============================] - 48s 4ms/step - loss: 1.2534 - accuracy: 0.3976 - val_loss: 1.3658 - val_accuracy: 0.5047
Epoch 13/20
12099/12099 [==============================] - 48s 4ms/step - loss: 1.2379 - accuracy: 0.4023 - val_loss: 1.5218 - val_accuracy: 0.3968
Epoch 14/20
12099/12099 [==============================] - 48s 4ms/step - loss: 1.2353 - accuracy: 0.4031 - val_loss: 1.2910 - val_accuracy: 0.5187
Epoch 15/20
12099/12099 [==============================] - 48s 4ms/step - loss: 1.2350 - accuracy: 0.4057 - val_loss: 1.3995 - val_accuracy: 0.5096
Epoch 16/20
12099/12099 [==============================] - 51s 4ms/step - loss: 1.2343 - accuracy: 0.4092 - val_loss: 1.3413 - val_accuracy: 0.5372
Epoch 17/20
12099/12099 [==============================] - 47s 4ms/step - loss: 1.2231 - accuracy: 0.4088 - val_loss: 1.3217 - val_accuracy: 0.4946
Epoch 18/20
12099/12099 [==============================] - 48s 4ms/step - loss: 1.2221 - accuracy: 0.4094 - val_loss: 1.4571 - val_accuracy: 0.4622
Epoch 19/20
12099/12099 [==============================] - 48s 4ms/step - loss: 1.2215 - accuracy: 0.4078 - val_loss: 1.2082 - val_accuracy: 0.5681
Epoch 20/20
12099/12099 [==============================] - 46s 4ms/step - loss: 1.2127 - accuracy: 0.4115 - val_loss: 1.2409 - val_accuracy: 0.5569
3781/3781 [==============================] - 9s 2ms/step - loss: 1.2474 - accuracy: 0.5553
Test Accuracy: 0.5553498268127441
3781/3781 [==============================] - 8s 2ms/step
              precision    recall  f1-score   support

           0       1.00      0.72      0.84      9576
           1       0.51      0.86      0.64      3635
           2       0.67      0.33      0.44     18328
           3       0.95      0.48      0.64     10429
           4       0.70      0.54      0.61     12120
           5       0.43      0.63      0.51      2822
           6       0.93      0.41      0.57      2461
           7       0.51      0.67      0.58      3470
           8       0.05      1.00      0.10       245
           9       0.47      0.30      0.37      4163
          10       1.00      0.77      0.87       632
          11       0.73      1.00      0.84      4161
          12       0.15      0.61      0.24      2201
          13       0.06      0.91      0.11       492
          14       0.54      0.90      0.68      1407
          15       0.65      0.91      0.76      2036
          16       0.23      1.00      0.37       287
          17       0.21      0.91      0.34      2073
          18       0.89      0.63      0.74     16119
          19       0.65      0.40      0.49     21672
          20       1.00      0.91      0.95      1836
          21       0.31      0.98      0.48       820

    accuracy                           0.56    120985
   macro avg       0.57      0.72      0.55    120985
weighted avg       0.71      0.56      0.59    120985

In [68]:
merged_data_s['duration_numeric'] = merged_data_s['duration'].astype(str).str.split(':').apply(lambda x: int(x[0]) * 60 + int(x[1]) if len(x) == 2 else np.nan)
merged_data_s= merged_data_s.drop(columns = ['duration'])

In [69]:
merged_data_s.fillna(0, inplace=True)

In [70]:
merged_data_s

,timestamp,step_detector_values,audio_value_1,audio_value_2,audio_value_3,audio_value_4,activity_type,duration_numeric
0,2017-06-29 07:45:16.506,1.0,0.0,0.00000,0.0,0.0,0,0.0
1,2017-06-29 07:45:17.407,0.0,0.0,0.00000,0.0,32767.0,0,0.0
2,2017-06-29 07:45:18.407,0.0,227.0,113.50000,227.0,227.0,0,0.0
3,2017-06-29 07:45:19.407,0.0,590.0,272.33334,590.0,227.0,0,0.0
4,2017-06-29 07:45:20.446,0.0,1724.0,635.25000,1724.0,227.0,0,0.0
...,...,...,...,...,...,...,...,...
617948,2017-07-13 20:13:33.671,0.0,1956.0,5246.24850,32767.0,30.0,Video games,41.0
617949,2017-07-13 20:13:34.663,0.0,2673.0,5246.18160,32767.0,30.0,Video games,41.0
617950,2017-07-13 20:13:35.663,0.0,2340.0,5246.10640,32767.0,30.0,Video games,41.0
617951,2017-07-13 20:13:36.668,0.0,2046.0,5246.02400,32767.0,30.0,Video games,41.0
617952,2017-07-13 20:13:37.668,0.0,2441.0,5245.95170,32767.0,30.0,Video games,41.0

In [77]:
# Assuming your DataFrame is named df
filtered_df_phone = merged_data_s[merged_data_s['duration_numeric'] == 0]

In [79]:
filtered_df_phone = filtered_df_phone.drop(columns = ['activity_type'])

In [80]:
filtered_df_phone

,timestamp,step_detector_values,audio_value_1,audio_value_2,audio_value_3,audio_value_4,duration_numeric
0,2017-06-29 07:45:16.506,1.0,0.0,0.00000,0.0,0.0,0.0
1,2017-06-29 07:45:17.407,0.0,0.0,0.00000,0.0,32767.0,0.0
2,2017-06-29 07:45:18.407,0.0,227.0,113.50000,227.0,227.0,0.0
3,2017-06-29 07:45:19.407,0.0,590.0,272.33334,590.0,227.0,0.0
4,2017-06-29 07:45:20.446,0.0,1724.0,635.25000,1724.0,227.0,0.0
...,...,...,...,...,...,...,...
13025,2017-06-29 09:56:58.449,0.0,6107.0,7546.25150,32767.0,45.0,0.0
13026,2017-06-29 09:56:58.497,1.0,0.0,0.00000,0.0,0.0,0.0
13027,2017-06-29 09:56:59.006,1.0,0.0,0.00000,0.0,0.0,0.0
13028,2017-06-29 09:56:59.447,0.0,6454.0,7546.11400,32767.0,45.0,0.0
13029,2017-06-29 09:56:59.784,1.0,0.0,0.00000,0.0,0.0,0.0

In [82]:
# Load the previously saved model
model = load_model('/Users/emilkoch/Desktop/2Tango/messenger/Research/Model_Save/smartphone.keras')

# Prepare the features from the unlabeled data
X_unlabeled = filtered_df_phone[['duration_numeric', 'step_detector_values', 'audio_value_1', 'audio_value_2', 'audio_value_3', 'audio_value_4']]

# Preprocess unlabeled data (assuming you've already standardized the features)
X_unlabeled_scaled = scaler.transform(X_unlabeled)

# Make predictions
y_pred = model.predict(X_unlabeled_scaled)

# Inverse transform the predicted labels
decoded_labels = label_encoder_smartphone.inverse_transform(np.argmax(y_pred, axis=1))

# Add the decoded labels to the DataFrame
filtered_df_phone['predicted_activity'] = decoded_labels

408/408 [==============================] - 1s 2ms/step

In [83]:
filtered_df_phone

,timestamp,step_detector_values,audio_value_1,audio_value_2,audio_value_3,audio_value_4,duration_numeric,predicted_activity
0,2017-06-29 07:45:16.506,1.0,0.0,0.00000,0.0,0.0,0.0,Walk
1,2017-06-29 07:45:17.407,0.0,0.0,0.00000,0.0,32767.0,0.0,Running
2,2017-06-29 07:45:18.407,0.0,227.0,113.50000,227.0,227.0,0.0,Walk
3,2017-06-29 07:45:19.407,0.0,590.0,272.33334,590.0,227.0,0.0,Walk
4,2017-06-29 07:45:20.446,0.0,1724.0,635.25000,1724.0,227.0,0.0,Walk
...,...,...,...,...,...,...,...,...
13025,2017-06-29 09:56:58.449,0.0,6107.0,7546.25150,32767.0,45.0,0.0,Took off glasses
13026,2017-06-29 09:56:58.497,1.0,0.0,0.00000,0.0,0.0,0.0,Walk
13027,2017-06-29 09:56:59.006,1.0,0.0,0.00000,0.0,0.0,0.0,Walk
13028,2017-06-29 09:56:59.447,0.0,6454.0,7546.11400,32767.0,45.0,0.0,Took off glasses
13029,2017-06-29 09:56:59.784,1.0,0.0,0.00000,0.0,0.0,0.0,Walk